version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    image: 'ssp'
    container_name: ${APP_NAME}_api
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - database

  database:
    image: postgres
    container_name: ${APP_NAME}_database
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  pgadmin:
    container_name: ${APP_NAME}_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    ports:
      - "5051:80"
